<?php 
session_start();
require 'redir.php';
require 'menuf.php';
?>
<html>
    <head>
        <title>Help Page</title>
        <!-- <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css"> -->
        <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
        <link rel="stylesheet" href="style.css">
        <script type="text/javascript">
            $(document).ready(function(){
                $("#hide").click(function(){
                    $("#kamuri").hide();           
                });
                $("#show").click(function(){
                    $("#kamuri").show();           
                });
            });
        </script>
        <!-- <style>
            body{
                background-image: url("img3.png");
                background-repeat: no-repeat;
                background-position: right top;
                background-size:230px;
            }
        </style> -->
    </head>
    <body class='body_help'>
        <div class='img_help'>
            <img src="img3.png" alt="kawaii_yo" usemap="#map1" id='kamuri'>
            <abbr title="トレジャーを発見します!">
            <map name="map1" >
                <area shape="rect" coords="80,100,150,150" href="https://slow-start.com/" alt="kamuri" target="_blank">
            </map>
            </abbr>
            <br>
            <button id='hide' style='position:absolute; right:50px;'>Hide</button>
            <button id='show' style='position:absolute; right:0px;'>Show</button>
        </div>
        <div>
            <h2>Help Page</h2>
            (In this page we provide general help and <u>instructions</u> on how to use this website)
            <h4>General Instrutions</h4>
                <p>
                    This website supports some basic functions to search properties and select specific compounds. By default, website will automatically select all suppliers. So users are recommended to select the Suppliers/Manufactures at first. The second step would generally be 'Stats and Histogram' which  helps users to check and decide what kind of properties can they use and decide the range they want to search.
                </p>
                <p>
                    <b>MW</b>: molecular weight; <b>TPSA</b>: The Polar Surface Area; <b>XlogP</b>: Estimated LogP;
                </p>
            <hr>
            <h4>Menu</h4>
                <p>
                    'Hide/Show' button can hide or show menu. 'Back to top' can make the page jump back to top.
                </p>
                <br>
            <h4>Stats and Histogram:</h4>
                <p>
                    This function can show the basic statistics (including count number, minimum value, maximum value, 25% or 50% or 75% quantiles, standard deviation, average) and distribution (a histogram generated by 'matplotlib' package in Python) of a selected attribute ('Stats for') of compound. Users can clearify the searching range by inputing 'Selection Range'. If nothing is entered in 'Selection Range', system will calculate the distribution of all compounds of selected suppliers. 'Closed Interval' provides the choices for users to decide whether to use open or closed interval at both sides. However, infinite range is not supprted, so please use number '0' as negative infinity or '999999' as positive infinity. 
                </p>
            <br>
            <h4>Corr and Heatmap:</h4>
                <p>
                    This function can show the pearson correlations heatmap (generated by 'seaborn' package in Python) across several attributes (chosen in "Corr across") of the compounds in selected range. Note that suppliers will also be considered in the retrieval conditions. Users should at least select one properties in 'Corr across' to get a result. It's highly recommended that users just enter the search range and select all properties in 'Corr across'.
                </p>
            <br>
            <h4>Search Structure:</h4>
                <p>
                    This function can retrieve compounds catalog id, SMILES string and 2D structure by selecting specific range of atoms chosen by users. Users can use 'Stats and Histogram' to check the distribution in advance. Note that, for range selections ('Closed Interval'), users can decide whether to use open or closed interval at both sides. However, infinite range is not supprted, so please use number '0' as negative infinity or '999999' as positive infinity. To ensure the speed, currently we can not provide the results with more than 100, please use function 'Stats and Histogram' to check the count first. In terms of the result, users can click the ID in 'Catalogue ID' and view the 3D structure of selected compounds. (This function is built on Jmol module, see http://www.jmol.org/ for more manipulation helps) Users can also click the SMILES string in 'SMILES String' column to do a similarity search for compounds in ChEMBL database. By default, system uses 50% similarity as threshold. This will jump a 'similarity search' page that shows the results.(To save resource, system can only show the top 20 results.) Users can click the column name of 'Similarity' for sorting table by similarity By default, the table shows in decrease order of similarity. Users can click the ChEMBL ID at first column and jump directly to the page of that compound in ChEMBLE Website. ('Similarity search' function is built on using the api of ChEMBL, see https://www.ebi.ac.uk/chembl/.); Besides searching by limiting the properties of compounds, users can also directly search compounds which belong to the selected suppliers. This can be achieve by using the function 'Serach by Catalogue ID:' at the right. Users can search multiple Catalogue ID by seperating each ID with ',' for exemple: SPH1-000-419,SPH1-002-081,SPH1-002-085 (Supplier: Oai40000). If users want to get the table, click 'Download Table as CSV file' button on the top of the table. (Pictures in 'Structure' column will be blank in downloaded file)
                </p>
            <br>
            <h4>Search Properties:</h4>
                <p>
                    This function is almost the same as function 'search by atoms', but it can returns all properties of compounds from a set of selected conditions. Results will be in a table where users can click the column names for sorting of that column. To ensure the speed, currently we can not provide the results with more than 10000, please use function 'Stats and Histogram' to check the count first. Users can click the ID in 'Catalogue ID' and view the 3D structure of selected compounds. (This function is built on Jmol module, see http://www.jmol.org/ for more manipulation helps); Besides searching by limiting the properties of compounds, users can also directly search compounds which belong to the selected suppliers. This can be achieve by using the function 'Serach by Catalogue ID:' at the right. Users can search multiple Catalogue ID by seperating each ID with ',' for exemple: SPH1-000-419,SPH1-002-081,SPH1-002-085 (Supplier: Oai40000). If users want to get the table, click 'Download Table as CSV file' button on the top of the table.
                </p>
            <br>
            <h4>All Info by Suppliers:</h4>
                <p>
                    This function can show all attributes of compounds provided by selected suppliers. Results will be in a table where users can click the column names for sorting of that column. If users want to get the table, click 'Download as CSV' button on the top of the table. Users can select which columns to show in 'Select Column'. Users can limit the results by creating filter conditions in 'Search Builder'. 
                </p>
            <hr>
            <h4>Acknowledgement</h4>
                <p>
                    All codes are modified from the scripts provided in course: 'Introduction to Website and Database Design for Drug Discovery' lectured by Dr. Paul Taylor. The author of this website is Runling Chen.
                </p>
                <p>
                    2D structure images of compounds are source from 'https://cactus.nci.nih.gov/chemical/structure/'.
                </p>
                <p>
                    The following javascript libraries were used, library names and source web sites are given:
                    <ul>
                    <li>
                        jQuery: https://jquery.com/
                    </li>
                    <li>
                        Jmol: an open-source Java viewer for chemical structures in 3D. http://www.jmol.org/
                    </li>
                    <li>
                        ChEMBL: https://www.ebi.ac.uk/chembl/
                    </li>
                    <li>
                        TableSorter: https://mottie.github.io/tablesorter/
                    </li>
                    <li>
                        DataTable: https://datatables.net/
                    </li>
                    </ul>
                </p>
        </div>
    </body>
</html>